services:
  postgres:
    image: postgres:15-alpine
    container_name: ecg_postgres
    restart: always 
    environment:
      POSTGRES_USER: ${DATABASE_USER:-ecg_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-ecg_pass}
      POSTGRES_DB: ${DATABASE_NAME:-ecg_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-ecg_user} -d ${DATABASE_NAME:-ecg_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: ecg_mqtt_broker
    restart: always
    ports:
      - "1883:1883" 
    volumes:
      - ./mosquitto/config/:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  backend:
    build: .
    container_name: ecg_backend
    restart: always
    ports:
    - "5000:5000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER:-ecg_user} 
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-ecg_pass}
      DATABASE_NAME: ${DATABASE_NAME:-ecg_db}
  
      MQTT_BROKER: mosquitto 
      MQTT_PORT: 1883
      MQTT_USERNAME: "admin"    
      MQTT_PASSWORD: "ecgctai"

      MODEL_PATH: ${MODEL_PATH}
      FLASK_PORT: 5000
    
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

volumes:
  postgres_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
